PUT https://of1jog9c5g.execute-api.ap-southeast-1.amazonaws.com/testing/todos
Content-Type: application/json

{
    "id": "1",
    "title": "Build React App using Typescript",
    "completed": false
}